### ISSUE TITLE
Buying token example error

### ISSUE THREAD

**Issue by bcxyz** [wen-moon-ser/moonshot-bot-examples#7]
```
yarn run v1.22.22
$ tsc -p tsconfig.build.json
--- Buying token example ---
Error: Account does not exist or has no data 3YWuuUhmci8ShkrCeuHkhzgkdiagfyTwgcXYhy6WUzsV
    at AccountClient.fetch (/home/sniper/moonshot-bot-examples/node_modules/@coral-xyz/anchor/dist/cjs/program/namespace/account.js:120:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getCurveAccount (/home/sniper/moonshot-bot-examples/node_modules/@wen-moon-ser/moonshot-sdk/dist/solana/utils/getCurveAccount.js:9:26)
    at async PreloadedToken.init (/home/sniper/moonshot-bot-examples/node_modules/@wen-moon-ser/moonshot-sdk/dist/domain/model/token/PreloadedToken.js:20:30)
    at async buyIx (/home/sniper/moonshot-bot-examples/dist/src/buyIx.js:21:19)
    at async main (/home/sniper/moonshot-bot-examples/dist/src/index.js:7:5)
```

Trying to figure out where this error comes from, would like play around with your bot example

**Comment by mavagio** [comment]
hey @bcxyz there are 2 possible scenarios this error can throw:
1. If the token is just minted, it takes time before RPC nodes are caught up and some nodes might not see the newly minted token
2. If you use the wrong mint address, that is, the token was not created by Moonshot or the token has already been migrated to Raydium or Meteora, as after migration we remove the blockchain data about the token from Moonshot contract.
Hope this helps, feel free to reopen this issue if it didn't answer your question.

**Comment by bcxyz** [comment]
Im using this mint Address:
      mintAddress: '9ThH8ayxFCFZqssoZmodgvtbTiBmMoLWUqQhRAP89Y97',


I haven't find the issue as of yet
